### ISSUE TITLE
Biorhythm

### ISSUE THREAD

**Issue by Joeslinky** [asheliahut/ha-bedjet#5]
Would it be possible to support Biorhythm modes under the "Preset" menu?

**Comment by asheliahut** [comment]
It already supports the bio rhythm options under the "Preset" menu. 
![image](https://github.com/asheliahut/ha-bedjet/assets/945619/f67ac57b-0210-4be1-a475-336eb3aa614e)
The m1/m2/m3 are mapped to what they are set in your remote/app. So just set a biorhythm to one of those 3 buttons and use that @Joeslinky
