### ISSUE TITLE
Always Unavailable 

### ISSUE THREAD

**Issue by esmoyer** [asheliahut/ha-bedjet#6]
Just got my bedjet and excited when I saw this. Got everything setup, but when adding the bedjet, it's found but the device goes from unavailable to unknown. Getting this in the logs, any insight as to what I may be missing?

```
Logger: custom_components.bedjet.climate
Source: custom_components/bedjet/climate.py:294
integration: BedJet (documentation)
First occurred: March 8, 2024 at 6:02:09 PM (70 occurrences)
Last logged: 4:06:04 AM

Error "[org.bluez.Error.Failed] br-connection-canceled". Retrying in 10 seconds.
Error "". Retrying in 20 seconds.
Error "No backend with an available connection slot that can reach address B0:B2:1C:C4:F6:FA was found". Retrying in 10 seconds.
Error "No backend with an available connection slot that can reach address B0:B2:1C:C4:F6:FA was found". Retrying in 20 seconds.
Error "No backend with an available connection slot that can reach address B0:B2:1C:C4:F6:FA was found". Retrying in 30 seconds.
```

**Comment by asheliahut** [comment]
@esmoyer honestly, sometimes it is a crapshoot whether it connects or not. This has been a known issue for a long time. Sometimes when homeassistant restarts or aka the integration restarts it will start working. It is usually a 50/50 in my book. I just have never gotten around to try and figure out the bluetooth information enough of the bedjet to figure it out. The same issue exists with the original maintainer too. Not sure even how to start debugging it.

**Comment by esmoyer** [comment]
This is actually perfect timing. I just swapped over to Bluetooth proxy and it seems to work well. But, you're right, I have noticed after a restart I have to "reload" the config. Which isn't a big deal as I created an automation that runs after HA start to auto-reload the Bedjet configuration. So far, so good!

**Comment by jdsebo15** [comment]
Can you explain how you would swap over to Bluetooth proxy? I believe I have that capability and have a device near my BedJet that is capable I just don’t know how to get started.

**Comment by clf139** [comment]
Having the same issue. Been using Bluetooth proxy since initial setup so not. Sure why it’s unavailable. Did a redstart and a reload and the issue persists.

**Comment by asheliahut** [comment]
@esmoyer @jdsebo15 I have added some new logic that rechecks and validates the bedjets every minute. This should make the bedjets more findable if you have your bluetooth working. 

I will keep this open for awhile, but will end up closing assuming things get better for people.
