### ISSUE TITLE
Can't detect bedjets

### ISSUE THREAD

**Issue by Cals-tech** [asheliahut/ha-bedjet#8]
Hi! Thank you so much for this add-on, I hope I can get it working >< 

I'm pretty new to HA, so I'm sure I'm missing something simple, but I can't seem to add either of my bedjets to the Integration Entries. When I choose "Add Entry", I get the popup, but I don't know what information, if any, to provide: 

I've been trying to follow the config instructions provided, but I'm unclear what I'm doing wrong.  
![image](https://github.com/asheliahut/ha-bedjet/assets/67028875/aa558d9d-fa11-4261-b0df-125cd6e742b8)

I'm not sure what's meant by "follow the configuration flow in devices & services" but I navigated to the Integrations > BedJet page and tried "Add Entry"
<img width="442" alt="image" src="https://github.com/asheliahut/ha-bedjet/assets/67028875/e2180e14-0026-4b17-b15f-afdeddf97a0a">

If I leave it blank, I get the Success! box

<img width="436" alt="image" src="https://github.com/asheliahut/ha-bedjet/assets/67028875/5da4db4e-5f9a-4558-aa14-94ab6b40f291">

But then the list shows No devices or entities

<img width="1038" alt="image" src="https://github.com/asheliahut/ha-bedjet/assets/67028875/378c3901-cdbb-4e03-9e31-bf0f9ecebcb8">

When I enter the MAC address of my bedjet into the box, I get the success message again, but then the same result of "No devices or entities". 

Based on the issue tracker it doesn't seem like anyone else is getting stuck at this step, could you point me in the right direction? 

Thank you very much!

**Comment by monsieurlatte** [comment]
Do you have a bluetooth device to connect it to on your HA?  Also, I found that if my app was open and connected to the unit the HA wont detect it.

**Comment by asheliahut** [comment]
So @monsieurlatte @Cals-tech I pushed out an update that should help with detecting BedJets, It is now checking every 60 seconds for the bedjet and confirming it. Hopefully this will solve connectivity issues for people. I will leave this issue open for awhile to see if people see any better behavior.

**Comment by monsieurlatte** [comment]
Thanks, I wasn't having issues myself except for when I had the app open on my phone (which is expected).

**Comment by magicmanat1492** [comment]
Im having the same issuse as the person above me was... It will not show the device at all... Please help??

**Comment by monsieurlatte** [comment]
Have you put the device into pairing mode?

**Comment by magicmanat1492** [comment]
I cannot get the device to connect to my phone to save my life and I dont belive theres a possible way to put the bedjet into pairing mode..

**Comment by monsieurlatte** [comment]
Yes there is, it's in the instructions, there's a bluetooth pairing button on the bedjet itself.  https://imgur.com/a/UGTllX9

**Comment by magicmanat1492** [comment]
I put it into paring mode by pressing the button twice and it sill will not connect or show up...

**Comment by monsieurlatte** [comment]
Do you have a bluetooth proxy setup and running?

**Comment by magicmanat1492** [comment]
I do not. I was not aware this had to be true.. I will continue after getting that setup

**Comment by asheliahut** [comment]
I am going to go ahead and close this issue as this was due to a lack of having the bluetooth integration configured in homeassistant.
